// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoDev.Data.Contexto;

#nullable disable

namespace ProjetoDev.Data.Migrations
{
    [DbContext(typeof(ProjetoDevContexto))]
    [Migration("20240714001907_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjetoDev.Dominio.Dominio.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Curso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EscolaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Escola")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeAluno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EscolaId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("ProjetoDev.Dominio.Dominio.Escola", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeEscola")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Escolas");
                });

            modelBuilder.Entity("ProjetoDev.Dominio.Dominio.Aluno", b =>
                {
                    b.HasOne("ProjetoDev.Dominio.Dominio.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("EscolaId");

                    b.Navigation("Escola");
                });
#pragma warning restore 612, 618
        }
    }
}
